# Generated by Django 2.2.6 on 2019-10-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('console', models.CharField(choices=[('PS', 'Playstation'), ('XB', 'Xbox')], default='XB', max_length=2)),
                ('started', models.BooleanField()),
            ],
        ),
    ]
